dist: xenial
language: python
python:
- '3.7'
script:
- python application.py
notifications:
  slack:
    rooms:
      - secure: "guaZaMLZAIPOhTsymbarbna+DyFLbit3M828youAIqi/RLWtCbfBWjrhb2bgILrIzwIZEgcy2wMXpYnq08S1Ql0limu+NRHHCr4rCkj1QwghzZClq0bDjDkqdm8FxfPxgIvPR6Z2FAwABVUC/HhielPPJTZhl+jfOC06ngq3zYL/Dw37P4A0umAhRc1AfbErR52ie+ZWpaUC5Sz69vPEDogl9Z/NNI5U3bb56gx4k3ucMCG+FK11kB73aqT2xFZj5pGw82QunQKJN+QW05Kh3fTg3+pdxtGGFCtjfEBtdoBQIRu5iD1QX3ZT9oTM2+6awEjr62iinPV8TUm63F+qO8DCHIRzfHqKAZcy/5hO5q1xSg/e7M3/gROtW5LEJGGNS4ndZzLJEXydLXvPFh69Gd2Bq01vCPIPR7089D1QiZLPkUKopodzWKQdvFh1ZytwPYZVHZSKUDSmxHUMcEUD48amkkKmWoEInVe3H34ZAWbMOkH2EMgcIzCCwkVUZPP33WQPHxe2QI840tJqckacdd17nLt4fWd24lkIvTMNEB4tVU6vXxEARn2Wi/XkrdJh+WhIv7DYcmyvqTlxRI9oBanzayD3peCPSkLC1KFCRHyMfo1GC6iHC5YK5ES9vlsVF39Qmmrv53x6iADoAA7mYJnD5kT7RGbtYAiNe4PSu0I="
    on_success: always
    on_failure: always